language: ruby

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6.0-preview2
  - jruby-9.2.0.0

matrix:
  allow_failures:
    - rvm: jruby-9.2.0.0

bundler_args: --without development

services:
  - mongodb

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

sudo: false
