language: ruby

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head
  - jruby-9.2.5.0

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.5.0

jdk:
  - openjdk10

bundler_args: --without development

services:
  - mongodb

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

sudo: false
